[profile.default]
src = "contracts/src"
out = "out"
libs = ["dependencies", "../../contracts/src"]
test = "contracts/test"
script = "contracts/script"
evm_version = 'cancun'

[dependencies]
forge-std = "1.8.2"
"@openzeppelin-contracts" = "5.0.1"
