// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"bb001d441cb19c0439e5cb54ab7dd4d4e0cd8c4809abe8e19ba602b4ce8728dc9e2eafbe27eac14be5e561f6cd697429d0567a4f46f62291b58f541c46fbf653dff6725424ade3fdf1cc1014e062fa9e6c2e8e3a785fb2f84af10a44adfe761483b1036a00bea38909a90b4f557b520cc77f01a33000444dd2c5c572d590e03c55c646392b8f7d3f65ab4b05ce2a339f86210a1762d8cae53bafdeaa105949019e5fb72a17506d1c6db5cfbfee339cd9e20abc9871d2d72e6c0e66b9e8f6f5ddce73181022cc8347b8ac33a5ee18bb0cecf4d47225112e90e1c4d0b896b7ab77701a8f4c1391b544bc1d7ba20e6287ff63fded2de08e02db62b0093be54044819071cd65";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"39b8aec425bb4e7eb994a0e4b6e9dbeceba907cf70f463cba7dc9786fe2dfb86";
    bytes32 public constant USER_ID = hex"39b8aec425bb4e7eb994a0e4b6e9dbeceba907cf70f463cba7dc9786fe2dfb86";
}
