// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo run --bin set-inclusion-test-receipt -- --path [set-builder-elf-path]

pragma solidity ^0.8.13;

library TestSetInclusionReceipt {
    bytes public constant SEAL =
        hex"242f9d5b0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010473c457ba15c3c7fdb99bd1c573b7d69dd1a89c853b41f1d70367b2e912e0c3bf37c402fa2c54688484cc19db6aa6be1ad74c32b099a174bdd0a104048b3306b7bb69f28106e6fab490b2203cb8fe31cf65d540d9c2f8acbd926e542dcda59e39762b3d3f221f1a3223d8f6ccc540adc0c5780c597a814948fc6df6a344ab3b9c591e1daf0cbddc4bf49c4a29502895ec34ee618fce7e3106182957754058f2e97d7a8aa12756726c5616593b99a9bfc22effc123472ffa41b4a386399d62c612a858861c1c8ec04df3786dcc678ec8c330e2c814e4e30bfd1bd1db73c32937ac87d076942688845682345c812472026c6eb2271d125e001928ac2eeb4582b3c5e5fedec700000000000000000000000000000000000000000000000000000000";
    bytes public constant JOURNAL = hex"6500000063000000680000006f0000005f00000074000000650000007300000074000000";
    bytes32 public constant IMAGE_ID = hex"93795eafc980e752ecb2ba6ecb8203b2ff82794c5dc1d419847fea4300d76c8f";
}
