// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"000000000409dfc3c3cd9c37d7aba3a3d14c111071f90acd3c6ced448baeb4ffa40e22cd27c0df31c2b7321ae28fe445088e149f290f1693c31925bd72a37056cf04216d1d398b840b207a794869dc3d54726b5f0e741eff0d0357e533119e21e9e49b9612d0c02d75eeae7bc3323b40623263cc4e81324ff0f6d44284b0ec84060f0d5b1386f3743216891f373d034d899b706e56b624b395a8d54bd9fc807ccf6c7ed722e1373c9755eabf080ae51b035210db7f3e891220718ebfe7da08abfbf2daf905a428e3c4502b3682e346cd119f53a38d6f2e089127eac72838967b12905d081738cfb8ec514d25a5689c065afd5f86cf6d2151c7c178e530e9184506ab1a52";
    bytes32 public constant POST_DIGEST = hex"bf0db86ae1c21cd21fc975d15cf734c297e3b0ff0457398feaa2f24a43388bf5";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"186c3c822b99d0b11d4ee3cc74b13d38ca106e73644cb188df4a65dde8d06566";
}
