// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"c101b42b25016dc12080c5100a9841f324669460144c96d23619bb9e828e3a192c80ecfd1140eb491e6ba0b4b81afb4ff447e32cb9be3cecf003dc14959d680ae60dc11e040b0a98edd1abab11587de8a32f0095c37c7e43c03d7e5a709e0807c9c53a39127863b8b8ab606ee7527f4d1ff30a497b9c5c716b27946b68aad4408b6ab4d52bba359168a56baabe40a0da71463ccbeccab13c67e2029feb661b9e582cd1902fed2fbba2aa46f12326baf8e2b3bc85a413b25fed59692c4db8f6c3368bdbba2e0a48d161ea889d685b4ac1bd82c8ae190d35e656fd42d1086b362ad521acd22a62b65806ae08d4ca6ad0d6665bf8f4c9bd84717dc200adcd24e0cada3a621c";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"01ebed7f56116d9fdbae4a81c29c07daf43b17a1d5e4dd6eb0e971d689ccf88a";
}
