// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"9f39696c2c1cd42efd2ea081de900b08eb97ff95c2df709622928fdc93976baa4730a7502018b1654a232c0614a591ea42d8c210d63aa49c19a2009016b08255175d413712932a948d9569c41e39a7618fe801263768e32aa1780bff62c39432f208d66c272ea7ff083bceb60d70b317bbc6ae9656883ee1f3db197ffa4df9f581e7b8022acac6495e3dc193edf57762d43b460d767cb2f6bde5fb5f89097a7921622c0117c3c6f84a0d6e5cc251a9025a6812155c50212ed17c2dfab5c0805b5fa522cf08318d8bf05cba911dc6305dcd87ed1e90a0c27c80caaa05c0560871c8b6273c0333dfa7f0ca652760a1da866a2a9e222a87a422d988d5b75917be1ae4fbec67";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"192f3eb31ce4f578a52abb305490d63e4700f24fd460aa4cd4aa801e9672c869";
    bytes32 public constant USER_ID = hex"192f3eb31ce4f578a52abb305490d63e4700f24fd460aa4cd4aa801e9672c869";
}
