// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"f536085a1d323acff28d9c5ed9dc0cb8cf1b01f4596515aad4483ab8610b7c284f043ed81d74715567d7225580413feab5c59e32b0268bb290629957d06e1437bf2fb13f11b4d40f00a2e9a7462ff787fd9b8ebedbc22f25bc2a7be3a89394c00ed7018f02065b43f3e6ecec419f48bdd3f42f292503ccbca34a379b424af0a53cfe53660d693cbd13ee5ea7f38282d4d4be2a7bbdff3ba24cb460caa5b024bdb1f8003406b7d223e2110dab31b4194d5667e16264650924e1b5c00a1375b55318ed15732af940c906657fbc94daaad6da027941e0c01119bfe579ecd0431bf32065a1062d4d5e0f91c308a0ef80ed43fd14d8e84921a28214700ef8d6a8f02bea7e72a2";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"e462bc1dc34b9dfe4af9243a5fc56f0e5423a88ace7e575fa051364109a8bfa0";
}
