// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"8875b7f30a2957c015e12098e5a126aed057d8ab864c63bdac1320cca2b9ec3f971991a92c0a90de5b94653ed55e94a24c606cd3dbbd8b69e6f1729dc9dd7fab5befb95a0aa73a8a5ca95aca6021f3e5a7e29346e5cd2e5e8fe627d8db802494ec970f252bb11156420f8946cc3c71be28eb5c20857cd14c83e57f18a9b4d9303c119cdc289e374c85ec9baca9cb89fce5d5018cfbbbd50afa80f14642a36f0c00fccabb0595f4c5de5ff8a336b3d9c911c67e105f44c156ba071fb2c9726e4a9f2462892e1fe283e6117a23edb18e8b1e1be2e2b8d326014818c3eff8313d947fcea98d062b8c8ce556623ab6f3de02c06c3ea86a27d124f048a0cf241ddf8212e535d1";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"1d4a4681e0481a5ef1e1b077bc53a3c057994a8e755b3adcc032be0553a76f13";
    bytes32 public constant USER_ID = hex"1d4a4681e0481a5ef1e1b077bc53a3c057994a8e755b3adcc032be0553a76f13";
}
