// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo run --bin set-inclusion-test-receipt -- --path [set-builder-elf-path]

pragma solidity ^0.8.13;

library TestSetInclusionReceipt {
    bytes public constant SEAL =
        hex"0f63ffd50000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010473c457ba102091c92984d8f6d2eaa6949e023fa075798d962a0d27ea515a021ae3cd62de008873bbeccd3f86b2dce066be541f57262b6d92a5e86c7f4e8bf1c9b4d3bda2284af7793085e0db80e3d1fc1436e72fdc17107c2857e3f1c0bc65c91736c0212fefa3c6b06aff602f117d8a041a6fc0f0617318e77ee7ec6699e0cbdb8465632cd5d1c78bd5c0ad4966d26ad52396da2a874622b88350ce49465200a4a662f61cfd3f798047d955930eb10a9ee261e7efb36e21079e5f1927218a90828d259f15d106b2a71b42ef1a64fed385dde08f14ae2b84f97d9061198f07eb8611214d23e001de10bfac6a5c4933c2d5a6c84ea3f84c6be6910be5021bacebf4ff275600000000000000000000000000000000000000000000000000000000";
    bytes public constant JOURNAL = hex"6500000063000000680000006f0000005f00000074000000650000007300000074000000";
    bytes32 public constant IMAGE_ID = hex"93795eafc980e752ecb2ba6ecb8203b2ff82794c5dc1d419847fea4300d76c8f";
}
