// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"a7b87ed11163f1fdf5c6361a4d3b2b5a372d4f244609cf9ab992136b267713a94da08f2b2b6e2b73ddeff733b9a2a09fac96ed775b03380a11e94b248caccefdd568224522b1fca843daadaf317122f98fa893c7698f8ab1298d92c7c6cf2a2c1e2038ba2d1f1e09c237b0a9d9c49966a394e10ac618a9d4048c4adf6cb18eea1a40e04d09f1f61483063e3bcb24653cbd348b0987f9cef5078e72ba0771f987778f19022b5617f28a225ab8bb80db5fcc63368a9790e69a59cd31dcf3dae6c24dd9bf8b098955d5a24720543462e5a508528505c39b0be1fd79a468a3d2c1ee28ca6cef2f551c3389ec72c1ccf1c721d4912f1c29051eb5dc9a53d2905fad0215e4fbb8";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"10a9543ecbf9e8b605530d769b35e81d07385689dbf8b3f3d85784bd0639bfd3";
    bytes32 public constant USER_ID = hex"10a9543ecbf9e8b605530d769b35e81d07385689dbf8b3f3d85784bd0639bfd3";
}
