// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"14da014b1bc1c7bee98fb93de003d5fb1daa886c41314fb6ef3f55157d29f7bdc1e8c2e20d423b8d9a8c11e614074f746a941a0a997c014910973485786d296e25d9cbbc03ae16177eae378bd1e9d215066620d55cd7e6b414e6decc8a435f4e864818052d055d103946470958c68c63f3fe384b889bb86dab8f3663f8a27e512caa3ba5159192bd95eabb960361f3480aef917733a308e9427a0fd9c6942678803b3bd50096dee2f5cddefa6c22f7f6e34eb0b7d50252b90ce9f160c08fbde7a5878f20197b57ed0af46897dcb9951dbb415a30fe87aa14232a838c963ca2a22b2bbb4e1d0a35d534057091a61a84150b059c062baf3bd57bb03836034efa5ea97f5db7";
    bytes public constant JOURNAL = hex"6a75737420612073696d706c652072656365697074";
    bytes32 public constant IMAGE_ID = hex"b415345ad2864e4cd4ef1553dde28307671bd101ce61f8db3c991e5cad0d643c";
}
