[profile.default]
src = "contracts/src"
out = "out"
libs = ["../../lib", "../../contracts/src"]
test = "contracts/test"
script = "contracts/script"
ffi = true
fs_permissions = [{ access = "read-write", path = "./contracts/test/benchmarks"}]

[fuzz]
runs = 10
seed = '0x1234' 

