#!/bin/bash

set -eo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONTRACTS_DIR="${SCRIPT_DIR:?}/.."
SCRIPT_FILE="${SCRIPT_DIR}/Manage.s.sol"
FIREBLOCKS=0

POSITIONAL_ARGS=()
FORGE_SCRIPT_FLAGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
    -f|--fireblocks)
        FIREBLOCKS=1
        shift # past argument
        ;;
    --broadcast)
        FORGE_SCRIPT_FLAGS+=("$1") 
        shift
        ;;
    --verify)
        FORGE_SCRIPT_FLAGS+=("$1") 
        shift
        ;;
    -*|--*)
        echo "Unknown option $1"
        exit 1
        ;;
    *)
        POSITIONAL_ARGS+=("$1") # save positional arg
        shift # past argument
        ;;
    esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

echo "Loading environment variables from deployment_secrets.toml"
if [ -z "$RPC_URL" ]; then
    echo -n 'RPC_URL from deployment_secrets.toml: ' > /dev/stderr
    export RPC_URL=$(yq eval -e ".chains[\"${CHAIN_KEY:?}\"].rpc-url" $CONTRACTS_DIR/deployment_secrets.toml)
    [ -n "$RPC_URL" ] || exit 1
else
    echo -n "RPC_URL from env $RPC_URL"
fi
if [ -z "$ETHERSCAN_URL" ]; then
    echo -n 'ETHERSCAN_URL from deployment.toml: ' > /dev/stderr
    export ETHERSCAN_URL=$(yq eval -e ".chains[\"${CHAIN_KEY:?}\"].etherscan-url" $CONTRACTS_DIR/deployment.toml)
    [ -n "$ETHERSCAN_URL" ] || exit 1
else
    echo -n "ETHERSCAN_URL from env $ETHERSCAN_URL"
fi
if [ -z "$ETHERSCAN_API_KEY" ]; then
    echo -n 'ETHERSCAN_API_KEY from deployment_secrets.toml: ' > /dev/stderr
    export ETHERSCAN_API_KEY=$(yq eval -e ".chains[\"${CHAIN_KEY:?}\"].etherscan-api-key" $CONTRACTS_DIR/deployment_secrets.toml)
    [ -n "$ETHERSCAN_API_KEY" ] || exit 1
else
    echo -n "ETHERSCAN_API_KEY from env $ETHERSCAN_API_KEY"
fi

# Set our function. If the function is "help", or if the function is
# unspecified, then print some help.
SCRIPT_FUNCTION="${1:-help}"
if [ "${SCRIPT_FUNCTION:?}" == "help" ]; then
    echo "Usage:"
    echo "  bash ${0} <SCRIPT_FUNCTION> [--fireblocks] [--broadcast]"
    echo "See README.md for a list of functions"
    exit 0
fi

echo "Running ${SCRIPT_FILE:?}:${SCRIPT_FUNCTION:?}"

# Check for forge
if ! command -v forge &> /dev/null; then
    echo "forge not found"
    exit -1
fi

# NOTE: forge script only works in the contracts directory right now.
cd $CONTRACTS_DIR

if [ $FIREBLOCKS -gt 0 ]; then
    # Check for fireblocks
    if ! command -v fireblocks-json-rpc &> /dev/null
    then
        echo "fireblocks-json-rpc not found"
        exit -1
    fi

    # Run forge via fireblocks
    fireblocks-json-rpc --verbose --rpcUrl ${RPC_URL:?} --http --apiKey ${FIREBLOCKS_API_KEY:?} -- \
        forge script ${SCRIPT_FILE:?}:${SCRIPT_FUNCTION:?} \
        --slow --unlocked ${FORGE_DEPLOY_FLAGS} ${FORGE_SCRIPT_FLAGS} \
        --rpc-url {}
else
    # Run forge
    forge script ${SCRIPT_FILE:?}:${SCRIPT_FUNCTION:?} \
        --slow ${FORGE_DEPLOY_FLAGS} ${FORGE_SCRIPT_FLAGS} \
        --private-key ${DEPLOYER_PRIVATE_KEY:?} \
        --rpc-url ${RPC_URL:?}
fi
