name: cargo risczero install
description: Install cargo risczero, build toolchains, and r0vm.

inputs:
  version:
    description: |
      crates.io version specifier to use when installing cargo-risczero

      Mutually exclusive with ref.
    required: false
    type: string
  ref:
    description: |
      Git reference to pull from risc0/risc0 and build'

      Mutually exclusive with version.
    required: false
    type: string
  toolchain-version:
    description: 'Version of the RISC Zero toolchains to install'
    required: false
    default: ''
    type: string
  features:
    description: 'Comma separated list of feature flags to set when building cargo risczero'
    required: false
    default: 'default'
    type: string

runs:
  using: composite
  steps:
    - name: validate inputs
      shell: bash
      run: |
        if [ ! -z "${{ inputs.version }}" ] && [ ! -z "${{ inputs.ref }}" ]; then
          echo "Error: Cannot specify both 'version' and 'ref' parameters"
          exit 1
        fi
        if [ -z "${{ inputs.version }}" ] && [ -z "${{ inputs.ref }}" ]; then
          echo "Error: Must specify either 'version' or 'ref' parameter"
          exit 1
        fi

    # Only run these steps if using ref (building from source)
    - name: checkout risc0
      if: inputs.ref != ''
      uses: actions/checkout@v4
      with:
        repository: 'risc0/risc0'
        path: 'tmp/risc0'
        ref: ${{ inputs.ref }}
        lfs: true
    - name: install active Rust toolchain
      if: inputs.ref != ''
      run: rustup toolchain install
      working-directory: tmp/risc0
      shell: bash
    - name: install cargo-risczero from git
      if: inputs.ref != ''
      run: cargo install --locked --path risc0/cargo-risczero --no-default-features --features "${{ inputs.features }}"
      working-directory: tmp/risc0
      shell: bash
    - name: install r0vm from git
      if: inputs.ref != ''
      run: cargo install --locked --bin r0vm --path risc0/cargo-risczero --features "${{ inputs.features }}"
      shell: bash
      working-directory: tmp/risc0
    - name: install toolchains
      if: inputs.ref != ''
      run: |
        cargo run --bin rzup -- install --verbose --force rust ${{ inputs.toolchain-version }}
        cargo run --bin rzup -- install --verbose cpp
      shell: bash
      working-directory: tmp/risc0

    # Only run this step if using version (installing from crates.io)
    - name: install cargo-risczero from crates.io
      if: inputs.version != ''
      run: cargo install --locked cargo-risczero --version "${{ inputs.version }}" --no-default-features --features "${{ inputs.features }}"
      shell: bash
    - name: install rzup
      if: inputs.version != ''
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH
      shell: bash
    - name: install r0vm
      if: inputs.version != ''
      run: rzup install --verbose r0vm ${{ inputs.version }}
      shell: bash
    - name: install toolchains
      if: inputs.version != ''
      run: |
        rzup install --verbose --force rust ${{ inputs.toolchain-version }}
        rzup install --verbose cpp
      shell: bash

    - name: cleanup
      run: rm -rf tmp
      shell: bash
