name: Bonsai integration

on:
  pull_request:
    branches: ["release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: r0.1.79.0-2
  RISC0_MONOREPO_REF: "release-1.1"

jobs:
  e2e-test:
    runs-on: [self-hosted, prod, "${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            feature: default
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: risc0/risc0/.github/actions/rustup@main
      - uses: risc0/risc0/.github/actions/sccache@main
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}
      - uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ./.github/actions/cargo-risczero-install
        with:
          ref: ${{ env.RISC0_MONOREPO_REF }}
          toolchain-version: ${{ env.RISC0_TOOLCHAIN_VERSION }}
          features: ${{ matrix.feature }}
      - name: build erc20-Counter
        run: cargo build
        working-directory: examples/erc20-counter
      - name: test erc20-Counter
        run: ./test-local-deployment.sh
        env:
          BONSAI_API_URL: ${{ secrets.BONSAI_API_URL }}
          BONSAI_API_KEY: ${{ secrets.BONSAI_API_KEY }}
        working-directory: examples/erc20-counter
      - run: sccache --show-stats
