[profile.default]
src = "contracts/src"
out = "out"
libs = ["../../lib", "../../contracts/src"]
test = "contracts/test"
script = "contracts/script"
evm_version = 'cancun'

[fmt]
line_length=120
wrap_comments=true
